extensions: 
  - alefragnani.Bookmarks
  - cweijan.vscode-mysql-client2
  - eamodio.gitlens
  - ecmel.vscode-html-css
  - esbenp.prettier-vscode
  - firefox-devtools.vscode-firefox-debug
  - formulahendry.auto-rename-tag
  - ms-azuretools.vscode-docker
  - ms-vscode.js-debug-nightly
  - ms-vscode.live-server
  - mtxr.sqltools
  - patbenatar.advanced-new-file
  - pranaygp.vscode-css-peek
  - redhat.fabric8-analytics
  - redhat.java
  - redhat.vscode-server-connector
  - redhat.vscode-community-server-connector
  - VisualStudioExptTeam.vscodeintellicode
  - vscjava.vscode-java-debug
  - vscjava.vscode-java-dependency
  - vscjava.vscode-java-pack
  - vscjava.vscode-java-test
  - vscjava.vscode-maven
  - dineug.vuerd-vscode
  - richterger.perl
  
